version: "3.8"

services:
    gateway:
        image: nginx:alpine
        container_name: quickpoll_gateway
        ports:
            - "5050:80"
        volumes:
            - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
        depends_on:
            - api

    api:
        build: .
        container_name: quickpoll_api
        volumes:
            - .:/usr/src/app
            - /usr/src/app/node_modules
        environment:
            - NODE_ENV=development
            - PORT=5000
            - MONGO_URI=mongodb://db:27017/quickpoll
            - JWT_SECRET=super_secret_poll_key_123
        depends_on:
            - db

    db:
        image: mongo:6.0
        container_name: quickpoll_dbx
        ports:
            - "27101:27017"
        volumes:
            - mongo_data:/data/db

volumes:
    mongo_data:
